repos:
  - repo: https://github.com/PyCQA/bandit
    rev: "1.7.9" # Update me!
    hooks:
      - id: bandit
        args: ["-c", "pyproject.toml"]
        additional_dependencies: ["bandit[toml]"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.6.3"
    hooks:
      - id: ruff
        args: ["--fix", "--extend-select", "I"]
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.11.2" # Use the sha / tag you want to point at
    hooks:
      - id: mypy
        args: [--strict, --ignore-missing-imports]
        additional_dependencies:
          - "backoff>=2.2.1"
