repos:
  - repo: https://github.com/PyCQA/bandit
    rev: "1.7.9" # Update me!
    hooks:
      - id: bandit
        args: ["-c", "pyproject.toml"]
        additional_dependencies: ["bandit[toml]"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.6.3"
    hooks:
      - id: ruff
        args: ["--fix", "--extend-select", "I"]
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.11.2" # Use the sha / tag you want to point at
    hooks:
      - id: mypy
        args: [--strict]
        additional_dependencies:
          - "backoff>=2.2.1"
          - "beautifulsoup4>=4.12.3"
          - "jinja2>=3.1.4"
          - "lxml>=5.3.0"
          - "mypy>=1.11.2"
          - "pre-commit>=3.8.0"
          - "psutil>=6.0.0"
          - "pydantic>=2.9.1"
          - "pytest>=8.3.2"
          - "python_mermaid>=0.1.3" # underscore is smaller than lower case letters
          - "pythonnet>=3.0.3"
          - "requests>=2.32.3"
          - "structlog>=24.4.0"
