[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pbix_parsers"
version = "0.0.1"
dependencies = []
description = "PBIX Languages -> AST"
readme = "README.md"

[project.optional-dependencies]
dev = [
  "pre-commit>=3.8.0",
  "pytest>=8.3.2",
  "structlog>=24.4.0",
  "python_mermaid>=0.1.3",
]

[tool.doc8]
max-line-length = 120
file-encoding = "utf8"

[tool.ruff]
line-length = 120
preview = true
target-version = "py311"

[tool.bandit]
exclude_dirs = ["tests/**"]

[tool.mypy]
disable_error_code = "import-untyped"
